backend:
  name: git-gateway
  branch: main

# Uncomment the line below to enable local development
# local_backend: true

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: markdown
    format: yaml
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss Z", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss"}
      - {label: "Categories", name: "categories", widget: "list", default: []}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: ""
    create: true
    slug: "{{slug}}"
    extension: markdown
    format: yaml
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["page", "post"], default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", required: false, hint: "e.g., /about/"}
      - {label: "Body", name: "body", widget: "markdown"}

